### ISSUE TITLE
Network Aggregation

### ISSUE THREAD

**Issue by Arezoo-bz** [ual/ual_model_workspace#10]
It would be nice to add establishments data from MTC Bay Area so we get variables such as 'jobs_800m', 'jobs_400m', etc to include in our models.

**Comment by smmaurer** [comment]
Good point. Should it be @mxndrwgrdnr's `jobs_w_occup.zip` table?

https://berkeley.app.box.com/notes/282712547032

**Comment by Arezoo-bz** [comment]
Or bayarea_ual.h5 establishments table. I'm not sure exactly.

**Comment by smmaurer** [comment]
You could experiment! Here's where the data loading and network aggregations are defined:

[scripts/datasources.py](https://github.com/ual/urbansim_parcel_bayarea/blob/master/scripts/datasources.py)
[configs/network_aggregations.yaml](https://github.com/ual/urbansim_parcel_bayarea/blob/master/configs/network_aggregations.yaml)
[notebooks-sam/Explore-data.ipynb](https://github.com/ual/urbansim_parcel_bayarea/blob/master/notebooks-sam/Explore-data.ipynb)

**Comment by Arezoo-bz** [comment]
Thanks, Sam!
