### ISSUE TITLE
Data processing 

### ISSUE THREAD

**Issue by Arezoo-bz** [ual/ual_model_workspace#13]
Is there any way to update an orca table, not just a column? 
Some critical steps in model making process such as data preprocessing, data transformation and feature engineering would be hard (inefficient) if the only way to update an orca table is by updating a single column.

**Comment by smmaurer** [comment]
Yes! I think the way I've seen this done is to re-register the dataframe with Orca, which replaces whatever was previously registered under that name. Something like this:

````py
df = orca.get_table('street_trees').to_frame()
# make changes to the dataframe
orca.add_table('street_trees', df)
````

Here's the full Orca API reference: http://udst.github.io/orca/core.html#api

**Comment by Arezoo-bz** [comment]
Thank you!
