### ISSUE TITLE
Replace relative path in Explore-data.ipynb with orca-specified DATA_DIR injectable

### ISSUE THREAD

**Issue by mxndrwgrdnr** [ual/ual_model_workspace#18]
Now that we are hosting the data in a central location on Rome, we should update all model steps that reference the location of the data directory to reference the orca injectable `DATA_DIR` rather than a relative path. Specifically, the `build_network()` step as defined [here](https://github.com/ual/urbansim_parcel_bayarea/blob/master/scripts/models.py#L20-L22) will cause problems down the line if a user follows the instructions [here](https://github.com/ual/urbansim_parcel_bayarea/blob/master/notebooks-sam/Explore-data.ipynb) to override the standard data directory. We should fix those two lines, and any other places where a relative path to a data directory is located.

**Comment by smmaurer** [comment]
Good catch, I missed those paths in #9. Feel free to fix this, or i can take care of it. The prior fixes in `datasources.py` can be a model: [datasources.py#L11-L26](https://github.com/ual/urbansim_parcel_bayarea/blob/master/scripts/datasources.py#L11-L26)

@mxndrwgrdnr, is `DATA_DIR` an injectable that already handles this, or are you referring to the `data_directory` injectable that i set up in this repo? I did a little digging just now for prior approaches to handling data location overrides, and don't see much. Here's some code in `urbansim` that codifies `/data` as the standard location, though, which is good to know about: [urbansim.utils.misc](https://github.com/UDST/urbansim/blob/master/urbansim/utils/misc.py#L14-L25).

**Comment by mxndrwgrdnr** [comment]
Sorry I'm not sure what corner of my brain I pulled `DATA_DIR` from. Definitely meant `data_directory`. I'll take care of this and submit a PR.
